name: Auto create release PR

on:
    # schedule:
    #     - cron: "0 05 * * FRI" #12:00 every Friday GMT+7
    pull_request:
        branches:
            - release/202**
        types:
            - closed

jobs:
    create-release-branch:
        runs-on: ubuntu-latest
        name: Get current release branch
        if: github.event.pull_request.merged == true
        outputs:
            current_release_branch: ${{ steps.current_release_branch.outputs.branch_name }}
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        
        - name: Get current release branch
          id: current_release_branch
          run: |
            set -e
            echo "::set-output name=branch_name::$(git branch --all --list '*origin/release/20*' | sort -r | head -n 1 | cut -c18-)"
    
    get-commit-dev-release:
        runs-on: ubuntu-latest
        name: Get number commit on dev and release branch
        needs: [create-release-branch]
        outputs:
            number_commit_dev: ${{ steps.count_commit.outputs.dev }}
            number_commit_release: ${{ steps.count_commit.outputs.release }}
            number_commit_feature: ${{ steps.count_commit.outputs.feature }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Get number commit on dev and release
            id: count_commit
            run: |
              set -e
              git checkout develop
              echo "::set-output name=dev::$(git rev-list --count develop)"

              git checkout ${{needs.create-release-branch.outputs.current_release_branch}}
              echo "::set-output name=release::$(git rev-list --count ${{needs.create-release-branch.outputs.current_release_branch}})"

              git checkout HEAD@{1}
              echo "::set-output name=feature::$(git rev-list --count develop..HEAD@{1})"
              git reflog
              echo "${{github.head_ref}}"
              echo git rev-list --count develop..${{github.head_ref}}

        
    calc-commit-before-merge-release:
        runs-on: ubuntu-latest
        name: Calc number commit before merge on release branch
        needs: [get-commit-dev-release]
        outputs:
           number_commit_before_merge: ${{ steps.calu_commit.outputs.before-commit }}
        steps:
          - name: Calu number commit before merge
            id: calu_commit
            run: |
                set -e
                echo "::set-output name=before-commit::$( expr ${{needs.get-commit-dev-release.outputs.number_commit_release}} - ${{needs.get-commit-dev-release.outputs.number_commit_feature}} )"
          

    generate-release-branch:
        runs-on: ubuntu-latest
        needs: [get-commit-dev-release, calc-commit-before-merge-release]
        name: Release branch for this week
        if: needs.get-commit-dev-release.outputs.number_commit_dev == needs.calc-commit-before-merge-release.outputs.number_commit_before_merge
        outputs:
            release-branch: ${{ steps.create-build-branch.outputs.branch }}
        steps:
            - name: Create branch
              id: create-build-branch
              run: |
                  if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] 
                  then
                    echo "::set-output name=branch::${{ github.event.inputs.release-branch }}"
                  else
                    echo "$(date -d 'next Wednesday' '+%Y%m%d')"
                    echo "::set-output name=branch::release/$(date -d 'next Wednesday' '+%Y%m%d')"
                  fi

    create-pull-request-from-release-branch:
        runs-on: ubuntu-latest
        name: Create Release PR
        needs: [generate-release-branch]
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                  fetch-depth: 0
                  persist-credentials: false
                  ref: "${{ needs.generate-release-branch.outputs.release-branch }}"

            - name: Create Pull Request
              id: cpr
              uses: repo-sync/pull-request@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
              with:
                  source_branch: "${{ needs.generate-release-branch.outputs.release-branch }}"
                  destination_branch: "develop"
                  pr_title: "[${{ github.event.inputs.jira-ticket-id }}] Release PR ${{needs.generate-release-branch.outputs.release-branch}}" # Title of pull request
                  pr_body: "This PR is auto-generated for this week ${{needs.generate-release-branch.outputs.release-branch}}" # Full markdown support, requires pr_title to be set
                  pr_label: "release,automated,Ok to test" # Comma-separated list (no spaces)
                  pr_draft: true # Creates pull request as draft
                  pr_allow_empty: true # Creates pull request even if there are no changes

            
