name: Auto create release PR

on:
    pull_request:
        branches:
            - release/202**
        types:
            - closed

jobs:  
    get-commit-diff:
        runs-on: ubuntu-latest
        name: Get number commit on dev and release branch
        outputs:
            number_commit_diff: ${{ steps.count_commit.outputs.diff }}
            current_release_branch: ${{ steps.current_release_branchs.outputs.current_branch }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Get number commit on dev and release
            id: count_commit
            run: |
              set -e
              git checkout develop        
              git checkout -b new-branch ${{ github.event.pull_request.base.sha }}
              echo "::set-output name=diff::$(git rev-list --count develop..new-branch)"

              echo commit_diff:
              git rev-list --count develop..new-branch
          
          - name: Get current release branch
            id: current_release_branchs
            run: |
                set -e
                echo "::set-output name=current_branch::$(git branch --all --list '*origin/release/20*' | sort -r | head -n 1 | cut -c18-)"

                echo "${{github.base_ref}}"
                git branch --all --list '*origin/release/20*' | sort -r | head -n 1 | cut -c18-

    create-pull-request-from-release-branch:
        runs-on: ubuntu-latest
        name: Create Release PR
        needs: [get-commit-diff]
        if: ${{ needs.get-commit-diff.outputs.number_commit_diff == 0 && github.base_ref == needs.get-commit-diff.outputs.current_release_branch}}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                  fetch-depth: 0
                  persist-credentials: false
                  ref: "${{github.base_ref}}"
      
            - name: Create Pull Request
              id: cpr
              uses: repo-sync/pull-request@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
              with:
                  source_branch: "${{github.base_ref}}"
                  destination_branch: "develop"
                  pr_title: "Release PR ${{github.base_ref}}" # Title of pull request
                  pr_body: "This PR is auto-generated for this week ${{github.base_ref}}" # Full markdown support, requires pr_title to be set
                  pr_label: "release,automated,Ok to test" # Comma-separated list (no spaces)
                  pr_draft: true # Creates pull request as draft
                  pr_allow_empty: true # Creates pull request even if there are no changes

            
